[package]
name = "arcaphyte-ether"
version = "0.1.0"
description = "A personal browser by Arcaphyte"
authors = ["Arcaphyte"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "3.0.0-alpha.3", features = [] }

[dependencies]
tauri = { version = "3.0.0-alpha.4", features = ["unstable"] }
tauri-runtime-cef = { version = "3.0.0-alpha.5", features = ["unstable"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
[features]
browser-test = []
