import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1380,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:1420');
await page.getByRole('heading',{name:'A world waiting to be discovered.'}).waitFor();
await page.screenshot({path:'test-results/ether-home.png',fullPage:true});
await page.getByRole('button',{name:'Themes',exact:true}).click();
await page.getByRole('button',{name:'Arcaphyte Midnight',exact:true}).click();
await page.getByLabel('Custom theme name').fill('Ocean test');
await page.getByRole('button',{name:'Save theme',exact:true}).click();
await page.reload();await page.getByRole('button',{name:'Themes',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'Ocean test',exact:true}).count(),1);
await page.getByRole('button',{name:'Ether Sky',exact:true}).click();
await page.getByRole('button',{name:'Close settings'}).click();
await page.getByRole('button',{name:'Profiles',exact:true}).click();
await page.getByLabel('Profile name',{exact:true}).fill('Austin');
await page.getByRole('button',{name:'Close settings'}).click();
await page.reload();assert.equal(await page.getByRole('button',{name:'✦ Austin'}).count(),1);
await page.getByRole('button',{name:'Settings',exact:true}).click();
await page.getByRole('combobox').selectOption('google');
await page.getByRole('button',{name:'Close settings'}).click();
await page.getByRole('textbox',{name:'Search the web',exact:true}).fill('crystal art');
await page.getByRole('button',{name:'Search',exact:true}).click();
await page.getByRole('heading',{name:'Desktop browser preview'}).waitFor();
assert.equal(await page.getByLabel('Address or search').inputValue(),'https://www.google.com/search?q=crystal%20art');
await page.getByRole('button',{name:'New tab',exact:true}).click();
assert.equal(await page.getByRole('tab').count(),2);
await page.getByRole('button',{name:'Bookmarks',exact:true}).click();
await page.getByLabel('Name',{exact:true}).fill('Example');
await page.getByLabel('Website address').fill('https://example.com');
await page.getByRole('button',{name:'Add bookmark',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'Remove Example',exact:true}).count(),1);
await page.getByRole('button',{name:'Remove Example',exact:true}).click();
await page.getByRole('button',{name:'Close settings'}).click();
await page.setViewportSize({width:900,height:650});
await page.screenshot({path:'test-results/ether-compact.png',fullPage:true});
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: themes, persistence, profile editing, engine choice, navigation, tabs, bookmarks, compact layout; no page errors.');

